name: "Deploy App"

on:
  push:
    branches: ["2-exercise"]

jobs:
  setup-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Test output console 
        uses: actions/checkout@v4
      - run: echo "Start deplaoy ..."
    
      - name: Installing Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Node version
        run: echo --version node

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java --version 
