name: "Deploy to server - github-actions [1-exercise]"

on:
  push:
    branches: ["1-exercise"]

jobs:
  first_jobs:
    name: 1-exercise
    runs-on: ubuntu-latest

    env:
      NAME: CarlosMartinez

    steps:
      - name: First Step - Hello world
        run: echo "Hello world from run"

      - name: Working dir before action
        run: ls -al

      - name: action
        uses: actions/checkout@v4 # root del proyecto actual

      - name: Working dir after action
        run: ls -al   

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'     

  second_jobs:
    #if: false # configuro que no se ejecute el step
    # github.ref return branch to execute
    #if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Second Step - Hello world
        run: echo "Hello world from run by $NAME"

      - name: test context
        run: echo ${{ github.ref }}

      - name: Github output 
        run: echo $GITHUB_OUTPUT