name: "Deploy to server - github-actions [1-exercise]"

on:
  push:
    branches: ["1-exercise"]

jobs:
  first_jobs:
    runs-on: ubuntulatest
    steps:
      - name: Hello world
      - run: echo "Hello world from run"