name: "Deploy App"

on:
  push:
    branches: ["2-exercise"]

jobs:
  job-build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Installing Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Node version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

      - name: Install Java
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java --version 

  job-deploy:
    runs-on: ubuntu-latest
    needs: job-build

    steps:

      - name: Deploy
        run: echo "Deploy..."
